name: edi_crud
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.4.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6

  permission_handler: ^11.0.1

  #* Background service
  # workmanager: ^0.5.1

  #* UI
  flash: ^3.0.5+1
  flutter_keyboard_visibility: ^6.0.0
  flutter_svg: ^2.0.0
  google_fonts: 6.1.0

  #* Dart data class
  freezed_annotation: ^2.2.0
  json_annotation: ^4.7.0
  # riverpod_generator: ^2.1.5

  #* Code generator
  riverpod: ^2.4.3
  riverpod_annotation: ^2.2.0

  #* State management
  flutter_hooks: ^0.20.4
  hooks_riverpod: ^2.4.3

  #* Logging
  logging: ^1.1.0

  #* Routing
  go_router: ^13.2.0

  #* Persistent storage
  shared_preferences: ^2.2.0
  sqflite: ^2.3.3+1

  #* UUID
  uuid: ^4.2.2

  #* Networking
  dio: ^5.4.3+1
  pretty_dio_logger: ^1.2.0-beta-1

  #* Misc
  collection: ^1.16.0
  dartz: ^0.10.1
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  #* Code generators
  build_runner: ^2.3.2
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.2.13
  freezed: ^2.2.1
  json_serializable: ^6.5.4
  riverpod_generator: ^2.3.3

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
